[tool.ruff]
line-length = 120
select = ["E", "F", "W", "I"]
fix = true

[tool.black]
line-length = 120  # Match PEP 8 (default: 88)
target-version = ['py311', 'py313']
skip-string-normalization = true  # Don't change single/double quotes
